### ISSUE TITLE
Problems with IFP_generation_examples_PDB.ipynb

### ISSUE THREAD

**Issue by PatWalters** [HITS-MCM/MD-IFP#1]
Hi,

First off thanks for releasing your code.  I found a couple of issues with IFP_generation_examples_PDB.ipynb. 

1. In the second cell of "1.4 Visualization of protein residues involved in the PL interactions", you state "Next, let us look at aromatic interactions".  It's unclear what is being shown here, everything appears to be obscured by the water. 

2.  At the bottom of the cell "2.1 Read a trajectory, compute PL IFPs and show results".  There is this line:
. = table_combine(df_HB, df_WB, df_prop, "INH")
which is a syntax error.  It looks like this should be
df_prop_complete = table_combine(df_HB, df_WB, df_prop, "INH")

3.  In the "Explanation of the Plots" at the bottom of section 2.1, it indicates that there are 3 plots, I only see 2, the fingerprint heatmap and the number of molecules participating in the water shells.

4.  There is an exception in section 2.4 because the variable water_bridges is not defined
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-7aae4bfa4a98> in <module>
      1 # obtain string that contains unique residues interacting with water
----> 2 watr = ''.join([resid+' ' for resid in np.unique(water_bridges.sele2_resid.values.astype(str))])
      3 
      4 # obtain residues that participate in aromatic interaction
      5 residues = ''.join([str(ifp[6:]+' ') for ifp in df_prop_complete.columns.tolist() 

NameError: name 'water_bridges' is not defined

**Comment by DKokh** [comment]
Hi Pat,
thanks a lot for the feedback ! 
I fixed these issues in the code (sorry for the a long delay)
