### ISSUE TITLE
gromacs file

### ISSUE THREAD

**Issue by haoxuanluo731** [HITS-MCM/MD-IFP#13]
I want ask a question,when i want to use MD-IFP to analysis trajectory produced from Gromacs and produced IFP datadbase,what files should I use,in your example I only find the .py for NAMD and the example for NAMD,don not find Trajectories.py and IFP generation.py for Gromacs

**Comment by jjmallen** [comment]
Good day,

were you able to figure out this one. I am having similar questions

**Comment by autodataming** [comment]
HSP90_Gromacs.zip - an archive that contains three pkl data sets of protein-ligand IFPs (for three HSP90 complexes; PDB ID: 5J64, 5J86, 5LQ9) generated from RAMD dissociation trajectories simulated using new Gromacs-RAMD engine (https://github.com/HITS-MCM/gromacs-ramd)

https://zenodo.org/api/records/3981155/files-archive  

HSP90_Gromacs.zip  are the dataset used by IFP generation.py for Gromacs.
