### ISSUE TITLE
Problems with IFP_generation_examples_TRAJ.ipynb

### ISSUE THREAD

**Issue by PatWalters** [HITS-MCM/MD-IFP#2]
I get an exception when running the cell below "2.2 Computation of PL IFPs for all equilibration trajectories (takes about 15 min)"

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-ec82a31cb34b> in <module>
     15 # Save and visualize the IFP dataframe to the specified location
     16 # In the RMSD plot, in addition to the protein and ligand (heavy atoms) RMSD, also RMSD of the protein fragments given as an input (auxi_selection) are shown
---> 17 IFP_table = tr.namd.IFP_save(tr.PRJ_DIR+out_name+"_NAMD_com.pkl")
     18 

~/software/MD-IFP/Scripts/Trajectories.py in IFP_save(self, file, subset)
    435             IFP_list = self.IFP_unify(subset)
    436   #          print("+++++++++++++++++",self.names,subset)
--> 437             n_auxi = len(r_subset[0].rmsd_auxi)
    438             for i,(tr_c,n_replica) in enumerate(zip(r_subset,n_subset)):
    439                     print("#  Replica:",i,n_replica)

IndexError: list index out of range

My Data directory looks like this 
Data
├── 2YKI
│   ├── 2YKI.pse
│   ├── 2yki.pdb
│   ├── 2yki_MOE.pdb
│   ├── ligand_2yki_MOE.mol2
│   └── ligand_2yki_MOE.pdb
├── 4MQT
│   ├── AMBER_eq
│   │   └── ORTO-CHL-prod8-NPT.pdb
│   ├── IXO.pdb
│   ├── RAMD
│   │   ├── Replica1
│   │   │   ├── Traj1
│   │   │   │   └── ORTO-CHL_108_ramd_016.dcd
│   │   │   └── Traj2
│   │   │       └── ORTO-CHL_104_ramd_016.dcd
│   │   └── Replica2
│   │       ├── Traj1
│   │       │   └── ORTO-CHL_111_ramd_016.dcd
│   │       └── Traj2
│   │           └── ORTO-CHL_105_ramd_016.dcd
│   └── moe.mol2
└── 6EI5
    ├── INH.pdb
    ├── amber2namd2.dcd
    ├── moe.mol2
    ├── ref-min.pdb
    └── ref.prmtop

**Comment by DKokh** [comment]
The cell "2.2 Computation of PL IFPs for all equilibration trajectories (takes about 15 min)" requires Equilibration datta from the archive   from NAMD_eq.tar.gz, i.e.  your Data directory should also contain this: 
Data
├── 4MQT
│        ├── AMBER_eq
│        │       └── ORTO-CHL-prod8-NPT.pdb
│        ├── IXO.pdb
│        ├── RAMD
│        ├── NAMD                        
│        │          ├── Replica1
│        │          │        └── ORT-CHL_repl.dcd

I added more infromation to the JN
