### ISSUE TITLE
Something wrong in Scripts/Clustering.py

### ISSUE THREAD

**Issue by xiaotianzhou1982** [HITS-MCM/MD-IFP#7]
Dear Prof. Kokh,
I cannot run IFP_generation_examples_TRAJ.ipynb, so I transfer it to IFP_generation_examples_TRAJ.py and run it in the linux system. When I first run the script I got a error:
**File "/da5/zhoufeng/software/MD-IFP-master/Scripts/Clustering.py", line 120, in remove_dissociated_parts
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')**
I searched the internet and found the answer, so I changed 
**df_tot_Repl_Traj = df_tot_Repl[df_tot_Repl.Traj == str(i)]
to
df_tot_Repl_Traj = df_tot_Repl[df_tot_Repl.Traj == float(i)]**
Then it can continue, however, another error shows up:
**Original size of the database:  (15600, 734)  trajectories: 52
Final size of the database:  (0, 734)
Traceback (most recent call last):
  File "IFP_generation_examples_Analysis.py", line 231, in <module>
    dist = np.sqrt((df_tot_org.COM_x.values-df_tot_org.COM_x.values[0])*(df_tot_org.COM_x.values-df_tot_org.COM_x.values[0])+(df_tot_org.COM_y.values-df_tot_org.COM_y.values[0])*(df_tot_org.COM_y.values-df_tot_org.COM_y.values[0])+(df_tot_org.COM_z.values-df_tot_org.COM_z.values[0])*(df_tot_org.COM_z.values-df_tot_org.COM_z.values[0]))
IndexError: index 0 is out of bounds for axis 0 with size 0**
I think the problem is with
**df_tot_org = remove_dissociated_parts(df_tot_org)**
After this command the df_tot_org has 0 lines. I noticed that Clustering.py is still under development. Do you have a new version of this script? Many thanks!

Fred

**Comment by DKokh** [comment]
df_tot_Repl.Traj  is of the string type , so changing "str(i)" to "float(i)"   does not solve the original problem, but introduces additional one instead.
I would suggest to try to change the following line:
s = np.sum(df_tot_Repl_Traj.values,axis=1)
to 
s = np.sum(df_tot_Repl.Traj.values.astype(int),axis=1)
